version: '3.7'
services:
  catgpt:
    container_name: catgpt
    image: "cr.yandex/crpf7egagcfe3js0dj2g/catgpt:v1"
    restart : always
    network_mode: "host"
  ua:
    container_name: ua
    image: "cr.yandex/yc/unified-agent"
    environment:
      PROC_DIRECTORY: "/ua_proc"
      FOLDER_ID: "b1gfku53i9bu5vo7dghr"
    volumes:
      - /proc:/ua_proc
      - /home/ubuntu/ua.config:/etc/yandex/unified_agent/conf.d/config.yml
    network_mode: "host"
