name: Build catgpt
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login in ct.yandex
        uses: docker/login-action@v3
        with:
          username: iam
          password: ${{ secrets.YANDEX_CR_TOKEN }}
          registry: cr.yandex
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: catgpt
          file: ./Dockerfile
          push : true
          tags: cr.yandex/crpf0t8174hc6c7l5r4m/catgpt:v1
